### ISSUE TITLE
Serial / UserIO options toggle broken

### ISSUE THREAD

**Issue by svirant** [MiSTer-DB9/Issues#8] opened 2021-02-23 04:12 UTC
I think I've discovered an issue with the past two releases of the NES and SNES cores in relation to Serial - SNAC /UserIO core menu options.  The SNES_20210121 and NES_20210114 releases work as expected.

Each have issues with enabling Serial when UserIO is Off.  I've also deleted any associated .CFG files in the configs directory to try and see if it was related, but doesn't seem to matter.

This is a screenshot of the January release of SNES and NES.  Notice how the option to enable "Serial" and "Serial Mode" is available when UserIO is Off?
![NES_correct](https://user-images.githubusercontent.com/62872229/108801041-8935d100-7549-11eb-882a-546ee99bf363.jpg)
![SNES_correct](https://user-images.githubusercontent.com/62872229/108801053-8dfa8500-7549-11eb-9fd6-7ea60b66a645.jpg)

In the latest releases "Serial" and "Serial Mode" are now completely greyed out. (behaves the same in the previous release of each as well)
![NES](https://user-images.githubusercontent.com/62872229/108800568-550de080-7548-11eb-9948-408c111f640f.jpg)
![SNES](https://user-images.githubusercontent.com/62872229/108800575-5939fe00-7548-11eb-8c3e-974af8d2b4de.jpg)

**Comment by Miguel-T80c** [comment] 2021-02-23 16:28
Please, check the NES_20210222 and the next SNES_20210223 releases.

**Comment by svirant** [comment] 2021-02-23 17:02
That fix looks promising for SNES.  I believe the same bug is true for the NES core here: https://github.com/MiSTer-DB9/NES_MiSTer/blob/e4569e76bd7b4b3387c19a650ca084985c6fcf39/NES.sv#L459 Remove "en216p" from the line?

**Comment by svirant** [comment] 2021-02-23 17:50
The new SNES_20210223 release fixes the greyed out Serial/UserIO options, but introduces another greyed out issue with "Vertical Crop" in the Audio & Video menu.  I believe "en216p" is meant to be somewhere in the "status_menumask" array, because it is now causing this new issue now that it has been removed.  The same would be true for the NES core.

![newbug](https://user-images.githubusercontent.com/62872229/108885139-47923e00-75bc-11eb-8f5e-61a5021501ea.jpg)

**Comment by Miguel-T80c** [comment] 2021-02-24 02:50
Indeed, the problem originated when the variable en216p was included in the "status_menumask" line. In the case of NES, after reviewing it, it does not seem to interfere with our menu options although the "Vertical Crop" and "Crop Offset options" (as now in SNES) appear disabled, but I also observe that after even deleting cfg files I observe that this circumstance also It occurs in the official cores so I consider that the problem is solved on our part.

**Comment by svirant** [comment] 2021-02-24 08:10
For NES - I discovered that the OSD menu logic needed to be updated because en216p, which was just recently added to status_menumask, changing the ordering.  "Serial Mode" menu option enable/disable was set to the inverse of "Vertical Crop" menu option.  When Vertical Crop is eligible for use, the "Serial Mode" menu item would be permanently greyed out.  You can break eligibility for Vertical Crop mode by setting vscale_mode=1 in mister.ini for example. (There are other ways too). After doing this, toggling the Vertical Crop option will disable it if it wasn't already. You will then notice that "Serial Mode" is now available for use.  I have created a PR for this as well.

**Comment by svirant** [comment] 2021-02-24 08:39
For SNES - Same issue as NES.  OSD menu logic needed a bit of updating because of the new en216p option.  When Vertical Crop requirements have been met for enabling, the option is disabled when the UserIO option is disabled/greyed out. I also created a PR for this.

**Comment by Miguel-T80c** [comment] 2021-02-24 09:29
Merged PR, thanx!

**Closed as completed** 2021-02-24 19:14 UTC
